global using Desfecho.AspNetCore;
global using FluentValidation;
global using Mediator;
global using Microsoft.AspNetCore.Diagnostics;
global using Microsoft.AspNetCore.Diagnostics.HealthChecks;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Diagnostics.HealthChecks;
global using Scalar.AspNetCore;
global using Serilog;
